### ISSUE TITLE
OSX / Linux?

### ISSUE THREAD

**Issue by murbard** [atomex-me/atomex.client.wpf#1]
WPF seems to be Windows only. Atomex.me mentions an upcoming OSX version, are you trying to compile WPF for OSX are are you porting the application to a different framework?

**Comment by matsakiv** [comment]
Sorry for a long reply. Yes, WPF is Windows only now. The core client library written in cross platform .NET standard. Therefore we only port the views and the views models. Now we have the following platforms:
* Web (ASP .NET Core Blazor + WebAssembly) - **testing**;
* OSX (ASP .NET Core Blazor + Electron) - **testing**;
* iOS (Xamarin) - **testing and preparation for publication in the AppStore**;
* Android (Xamarin) - **in developing**;
* Windows (WPF) - **in production**;

Technically we can now build for Linux by analogy with OSX using the Blazor + Electron.

We also consider building OSX and Linux versions through Xamarin in case if Blazor + Electron will have low performace. Until we have identified such problems.

**Comment by murbard** [comment]
Electron does have a reputation as a hog, any reason you can't straight up use the iOS/Android code you have with Xamarin.mac?

**Comment by matsakiv** [comment]
We had three options:
- use Xamarin native projects with shared business logic and a separate UI for each platform which is associated with native elements;
- use Xamarin.Forms to create a common but limited UI (as far as I know Xamarin.Forms for MAC is still in the form of a preview version and not all UI controls are implemented);
- use Electron for ready ASP .NET Blazor project;

Of course, I often heard about Electron's reputation, but also I heard about successful projects (vscode, slack) and in our situation, i think, it was the fastest and most effective solution. We can immediately start on all platforms, even on the Web.

In my understanding the first options is the best in terms of quality because using all the capabilities of each platforms is cool. And we will most likely come to it in the end but we will do this with ready-made applications and a feedback from the community.
